[build]
  command = "echo 'Build OK'"
  publish = "public"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Redirection de l'API vers la fonction
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200
