[build]
  command = "echo 'Build OK'"
  functions = "functions"
  publish = "public"

# Redirection de l'API vers la fonction
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200
